### ISSUE TITLE
Update documentation to reflect default folder is hidden by Windows

### ISSUE THREAD

**Issue by hangtime79** [IBMPredictiveAnalytics/Model_Random_Forest#1]
The default writeable folder for the predictive extensions (CFE files) is:
"C:\ProgramData\IBM\SPSS\Modeler\16\CDB"

The ProgramData folder is a hidden system folder by default, either you need to turn off "Hide System Folders" in Folder Options or put the direct path in the toolbar in order to navigate to that folder. This can be confusing. 

![image](https://cloud.githubusercontent.com/assets/2651677/7516407/0f74e3ac-f49d-11e4-95b9-1658891a18c7.png)

I would suggest adding a comment in the documentation about this. 

Another alternative is to place a CFE file in the "C:\Program Files\IBM\SPSS\Modeler\17\ext\lib" folder. Modeler will recognize the extension if it is placed here as well. However, you need to have Admin rights to copy a file to that location.

**Comment by aruizga7** [comment]
Good point, I will update the documentation today.

**Comment by aruizga7** [comment]
Updated in the Readme.me and the PDF. Thanks!
